---
title: Have coaches changed how they select which players to give more minutes to?
author:
  - name: Derek Corcoran
    email: derek.corcoran.barrios@gmail.com
    affiliation: Pontificia Universidad Catolica de Chile
    footnote: Corresponding Author
  - name: Nicholas M. Watanabe
    email: nmwatana@olemiss.edu
    affiliation: The University of Mississippi 
address:
  - code: Some Institute of Technology
    address: Department, Street, City, State, Zip
  - code: Another University
    address: Department, Street, City, State, Zip
abstract: |
  Since the NBA adopted the three point line in .

  It consists of two paragraphs.

bibliography: mybibfile.bib
output: rticles::elsevier_article
---

_Text based on elsarticle sample manuscript, see [http://www.elsevier.com/author-schemas/latex-instructions#elsarticle](http://www.elsevier.com/author-schemas/latex-instructions#elsarticle)_


The Elsevier article class
==========================

#### Installation

If the document class *elsarticle* is not available on your computer,
you can download and install the system package *texlive-publishers*
(Linux) or install the LaTeX package *elsarticle* using the package
manager of your TeX installation, which is typically TeX Live or MikTeX.

#### Usage

Once the package is properly installed, you can use the document class
*elsarticle* to create a manuscript. Please make sure that your
manuscript follows the guidelines in the Guide for Authors of the
relevant journal. It is not necessary to typeset your manuscript in
exactly the same way as an article, unless you are submitting to a
camera-ready copy (CRC) journal.

## Methods

All variables were scaled and centered [@bro2003centering] using the caret package [@kuhn2013applied].
We performed all of the analyses using R statistical Software (R Core Team 2016). We fitted the occupancy models were using the unmarked package (Fiske and Chandler 2011) and we ranked the models based on Akaike’s Information Criteria for small sample sizes (AICc) using the MuMin Package (Bartoń 2016). First, we selected the best detection probability model for each species by fitting all possible first order models while holding occupancy constant. Next, the detection portion of the model was fixed while the occupancy component of the model was selected following similar steps. Since both burn intensity measurements were highly correlated (>= 0.98 Pearson correlation coefficient), we did not allow those variables to coexist in the tested models. We expected non-linear relationships between fire intensity and occupancy, and thus we included both the linear and quadratic parameter of the burn intensity variables. We didn’t use model averaging since even though collinear variables were prohibited to coexist in the same model, these might coexist in the average model (Cade 2015). We projected the resulting occupancy model to the entire National Forest for each species included in this study and the best model for each species was assessed for goodness of fit using a Pearson Chi square statistic (MacKenzie and Bailey 2004). For each bat species, occupancy inside and outside of the fire areas was compared by with a t-test between the fitted values for the sampled points.

#### Functionality

The Elsevier article class is based on the standard article class and
supports almost all of the functionality of that class. In addition, it
features commands and options to format the

-   document style

-   baselineskip

-   front matter

-   keywords and MSC codes

-   theorems, definitions and proofs

-   lables of enumerations

-   citation style and labeling.

Front matter
============

The author names and affiliations could be formatted in two ways:

(1) Group the authors per affiliation.

(2) Use footnotes to indicate the affiliations.

See the front matter of this document for examples. You are recommended
to conform your choice to the journal you are submitting to.

Bibliography styles
===================

There are various bibliography styles available. You can select the
style of your choice in the preamble of this document. These styles are
Elsevier styles based on standard styles like Harvard and Vancouver.
Please use BibTeX to generate your bibliography and include DOIs
whenever available.

Here are two sample references: @barton2013mumin [@cade2015model].

References {#references .unnumbered}
==========
